iommu: Fix compilation issue if vendor hook is disabled
On some platform, vendor hook is disabled, then the function
register_trace_android_rvh_iommu_setup_dma_ops() is not defined,
this causes compilation error in dma-mapping-fast.c:
    error: implicit declaration of function
    'register_trace_android_rvh_iommu_setup_dma_ops'
    [-Werror,-Wimplicit-function-declaration].

Add to check the config in dma-mapping-fast.c.

Change-Id: I340335bbe7fc4c1d90a84f38067561d3671bf7a3
Signed-off-by: Qingqing Zhou <quic_qqzhou@quicinc.com>