msm: mhi_dev: Define debugfs APIs only if CONFIG_DEBUG_FS is enabled
Debugfs read and write APIs use global variables dbg_buff and
MHI_SM_MAX_MSG_LEN in mhi_sm layer. These variables are only declared if
CONFIG_DEBUG_FS is enabled. This is causing compilation issues in
perf_build if CONFIG_DEBUG_FS is not enabled.

Compilation errors:
1) mhi_sm.c:1581:22: error: use of undeclared identifier 'dbg_buff'
nbytes = scnprintf(dbg_buff, MHI_SM_MAX_MSG_LEN,
2) mhi_sm.c:1581:32: error: use of undeclared identifier
'MHI_SM_MAX_MSG_LEN'
nbytes = scnprintf(dbg_buff, MHI_SM_MAX_MSG_LEN,

To resolve these, defining debugfs read and write APIs only if
CONFIG_DEBUG_FS is enabled, as these APIs are used only if
CONFIG_DEBUG_FS is enabled.

Change-Id: Ibaff071803d952eebefe18df49f8a3ae5ce5c7ec
Signed-off-by: Sai Chaitanya Kaveti <quic_skaveti@quicinc.com>